[package]
name = "grand-music-cup"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.8.9", features = ["json", "macros"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["now"] }
clap = { version = "4.6.6", features = ["env", "derive"] }
const_format = "0.2.36"
dotenvy = "0.15.7"
http = "1.5.0"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
maud = { version = "0.27.0", features = ["axum", "axum-core"] }
rand = { version = "0.10.2", features = ["std_rng"] }
reqwest = { version = "0.13.4", features = ["form", "json"] }
rspotify = { version = "0.16.1", features = ["cli"] }
serde = { version = "1.0.229", features = ["rc"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.20"
time = "0.3.55"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7.0", features = ["cors"] }
url = "2.5.8"
urlencoding = "2.1.3"
